name: Code quality
on:
  push:
    branches: [ "main" ]
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-setup@v1
      - name: Build 
        uses: gradle/gradle-build-action@v2
        with:
          arguments: buildDebug
      - name: AndroidLint
        uses: dvdandroid/action-android-lint@master
        with:
          github_token: ${{ secrets.RTS_DEVOPS_GITHUB_TOKEN }}
          lint_xml_file: ./build/reports/android-lint.xml
          reporter: github-pr-review
      - name: detekt
        uses: alaegin/Detekt-Action@v1.21.0-RC2
        with:
          github_token: ${{ secrets.RTS_DEVOPS_GITHUB_TOKEN }}
          detekt_config: ./config/detekt/detekt-config.yml
