name: Publish demo nightly

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, ready_for_review]

jobs:
  Build-nightly:
    if: github.event.pull_request.draft == false
    name: Publish to firebase
    uses: ./.github/workflows/publish-demo.yml
    secrets:
        KEY_PASSWORD: ${{ secrets.DEMO_KEY_PASSWORD }}
        KEY_ALIAS: ${{ secrets.DEMO_KEY_ALIAS }}
        FIREBASE_CREDENTIAL_FILE_CONTENT: ${{ secrets.FIREBASE_CREDENTIAL_FILE_CONTENT }}
        FIREBASE_GROUP: ${{ secrets.NIGHTLY_GROUPS }}
        FIREBASE_APP_ID: ${{ secrets.NIGHTLY_APP_ID }}


