name: Release Pillarbox
on:
  workflow_dispatch:

jobs:
  PublishRelease:
    name: Build and upload library to Github packages
    uses: ./.github/workflows/publish-library.yml
    with:
      isSnapshot: false
    secrets: inherit
  UploadDemo:
    name: Upload Demo to Firebase AppDistribution
    uses: ./.github/workflows/publish-demo.yml
    secrets:
      KEY_PASSWORD: ${{ secrets.DEMO_KEY_PASSWORD }}
      FIREBASE_CREDENTIAL_FILE_CONTENT: ${{ secrets.FIREBASE_CREDENTIAL_FILE_CONTENT }}
      FIREBASE_GROUP: ${{ secrets.RELEASE_GROUPS }}
      FIREBASE_APP_ID: ${{ secrets.RELEASE_APP_ID }}
