name: Snapshot Pillarbox
on:
  workflow_dispatch:

jobs:
  PublishSnapshot:
    name: Build and upload library to Github packages
    uses: ./.github/workflows/publish-library.yml
    with:
      isSnapshot: true
    secrets: inherit
  UploadDemo:
    needs: PublishSnapshot
    name: Upload Demo to Firebase AppDistribution
    uses: ./.github/workflows/publish-demo.yml
    with:
      isSnapshot: true
    secrets:
        KEY_PASSWORD: ${{ secrets.DEMO_KEY_PASSWORD }}
        FIREBASE_CREDENTIAL_FILE_CONTENT: ${{ secrets.FIREBASE_CREDENTIAL_FILE_CONTENT }}
        FIREBASE_GROUP: ${{ secrets.NIGHTLY_GROUPS }}
        FIREBASE_APP_ID: ${{ secrets.NIGHTLY_APP_ID }}
